baseUrl: '@webBaseUrl'
enabled: '1'
handle: es
hasUrls: true
language: es
name: ES
primary: false
siteGroup: 1a35bfab-6a39-4c03-b273-2d5e3151c335 # Rubin Telescope Education and Public Outreach
sortOrder: 2
