columnSuffix: veruzkxg
contentColumnType: boolean
fieldGroup: 99f4a28a-48c3-49ca-bb4a-7acbb49fde30 # Pages
handle: domeStatus
instructions: null
name: 'Dome Status'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
