columnSuffix: null
contentColumnType: text
fieldGroup: 9940892d-32f4-4399-acac-ab559ce1c82b # Common
handle: plainText
instructions: null
name: 'Plain Text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: Text
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
