columnSuffix: wjpuqxra
contentColumnType: boolean
fieldGroup: 99f4a28a-48c3-49ca-bb4a-7acbb49fde30 # Pages
handle: weatherCondition
instructions: null
name: 'Weather Condition'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
