defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '@previewUrlFormat'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2c2e1c6a-eb4d-44f1-9a43-8d79b326f354:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{parent ? parent.uri : ''es''}/{slug}'
  547128fa-4529-4483-9968-66425996b69f:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 54619a73-dde0-4ec5-b77a-b6649f3a946b
type: structure
